import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppHeader } from "@/components/layout/AppHeader"; import { Screen } from "@/components/layout/Screen"; import { EmptyState } from "@/components/common/EmptyState";
import { getChapter, getChapterVerses, getTranslations } from "@/lib/content/service"; import type { Chapter, Verse } from "@/types/gita"; import { validateChapterNumber } from "@/lib/content/validation"; import { colors, radii, spacing, typography } from "@/constants/theme"; import { useLocalSetting } from "@/hooks/useLocalSetting"; import type { Language } from "@/constants/languages"; import { useAudio } from "@/components/audio/AudioProvider";
export default function ChapterDetailScreen(){const params=useLocalSearchParams<{chapterNumber:string}>();const router=useRouter();const chapterNumber=Number(params.chapterNumber);const[chapter,setChapter]=useState<Chapter|null>(null);const[verses,setVerses]=useState<Verse[]>([]);const[language]=useLocalSetting<Language>("settings.language","SANSKRIT");const{playQueue}=useAudio();useEffect(()=>{void Promise.all([getChapter(chapterNumber),getChapterVerses(chapterNumber)]).then(([c,v])=>{setChapter(c);setVerses(v)})},[chapterNumber]);if(!validateChapterNumber(chapterNumber)||!chapter)return <Screen><AppHeader title="Chapter not found" subtitle="Please choose a chapter from the list."/><EmptyState title="Invalid chapter" message="Valid chapters are 1 through 18."/></Screen>;
const playChapter=async()=>{const tracks=[];for(const verse of verses){let text=verse.sanskrit??"";if(language!=="SANSKRIT"){const t=await getTranslations(verse.id,language);text=t[0]?.text??"";}if(text)tracks.push({chapterNumber,verseNumber:verse.verseNumber,language,text})}await playQueue(tracks);};
return <Screen><AppHeader title={`Chapter ${chapter.chapterNumber}`} subtitle="Continuous chapter listening and verse navigation."/><View style={styles.card}><Text style={styles.title}>Chapter {chapter.chapterNumber}</Text><Text style={styles.description}>Play the chapter continuously in your selected language.</Text><Pressable onPress={()=>void playChapter()} style={styles.play}><Text style={styles.playText}>▶ Play Chapter</Text></Pressable></View><View style={styles.verseBox}><Text style={styles.heading}>{verses.length} verses</Text><View style={styles.list}>{verses.map(v=><Pressable key={v.id} style={styles.verse} onPress={()=>router.push(`/gita/verse/${chapterNumber}/${v.verseNumber}`)}><Text style={styles.verseTitle}>Verse {v.verseNumber}</Text><Text style={styles.verseText} numberOfLines={2}>{v.sanskrit}</Text></Pressable>)}</View></View></Screen>}
const styles=StyleSheet.create({card:{padding:spacing.lg,backgroundColor:colors.paper,borderRadius:radii.md,borderWidth:1,borderColor:colors.border},title:{color:colors.ink,fontSize:typography.h1,fontWeight:"800"},description:{color:colors.muted,fontSize:typography.body,lineHeight:24,marginTop:spacing.sm},play:{marginTop:spacing.lg,minHeight:52,paddingHorizontal:spacing.md,borderRadius:radii.pill,backgroundColor:colors.gold,alignItems:"center",justifyContent:"center"},playText:{color:colors.navy,fontWeight:"800"},verseBox:{marginTop:spacing.lg,padding:spacing.lg,borderRadius:radii.md,backgroundColor:colors.navy},heading:{color:colors.gold,fontSize:typography.h2,fontWeight:"800"},list:{marginTop:spacing.md,gap:spacing.xs},verse:{padding:spacing.md,borderRadius:radii.md,backgroundColor:"#ffffff12"},verseTitle:{color:colors.gold,fontWeight:"800"},verseText:{color:colors.ivory,lineHeight:22,marginTop:4}});
