import { useEffect } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Screen } from "@/components/layout/Screen";
import { useAuth } from "@/lib/auth/AuthProvider";
import { colors, radii, spacing } from "@/constants/theme";
const sections=["Books","Chapters","Verses","Translations","Audio","Commentaries","Users","Content Review"] as const;
export default function AdminDashboard(){ const router=useRouter(); const {user,loading}=useAuth(); useEffect(()=>{if(!loading&&user?.role!=="ADMIN")router.replace("/gita");},[loading,user,router]); if(loading)return <Screen><Text>Checking administrator access…</Text></Screen>; if(user?.role!=="ADMIN")return null; return <Screen><Text style={styles.title}>Admin Dashboard</Text><Text style={styles.muted}>Administrator-only content management. Publishing is blocked until content reaches the required review state.</Text><View style={styles.grid}>{sections.map(item=><Pressable key={item} accessibilityRole="button" accessibilityLabel={`Manage ${item}`} onPress={()=>item==="Translations"?router.push("/admin/translations"):item==="Audio"?router.push("/admin/audio"):undefined} style={styles.card}><Text style={styles.cardTitle}>{item}</Text><Text style={styles.cardText}>{item==="Translations"?"Create, edit, review and publish translations":`Manage ${item.toLowerCase()}`}</Text></Pressable>)}</View><Text style={styles.status}>Review statuses: Draft · Review Required · Human Reviewed · Published</Text></Screen> }
const styles=StyleSheet.create({title:{fontSize:30,fontWeight:"800",color:colors.ink},muted:{color:colors.muted,fontSize:14,lineHeight:22,marginTop:spacing.sm},grid:{gap:spacing.sm,marginTop:spacing.xl},card:{padding:spacing.lg,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.paper,minHeight:90},cardTitle:{fontSize:18,fontWeight:"800",color:colors.ink},cardText:{color:colors.muted,marginTop:spacing.xs,lineHeight:20},status:{marginTop:spacing.xl,color:colors.saffron,fontWeight:"800"}});
