import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { Screen } from "@/components/layout/Screen";
import { getVerse } from "@/lib/content/service";
import { getManagedTranslation, saveManagedTranslation, updateTranslationStatus, type ManagedTranslation } from "@/lib/admin/translationStore";
import { LANGUAGE_LABELS, TRANSLATION_LANGUAGES, type TranslationLanguage } from "@/constants/languages";
import type { Verse, ReviewStatus } from "@/types/gita";
import { colors, radii, spacing } from "@/constants/theme";
const statuses: ReviewStatus[]=["DRAFT","REVIEW_REQUIRED","HUMAN_REVIEWED","PUBLISHED"];
export default function AdminTranslations(){const router=useRouter();const [chapter,setChapter]=useState("1");const [verseNumber,setVerseNumber]=useState("1");const [language,setLanguage]=useState<TranslationLanguage>("KANNADA");const [verse,setVerse]=useState<Verse|null>(null);const [item,setItem]=useState<ManagedTranslation|null>(null);const [text,setText]=useState("");const [translator,setTranslator]=useState("");const [source,setSource]=useState("");const [license,setLicense]=useState("");const [notes,setNotes]=useState("");
const load=async()=>{const v=await getVerse(Number(chapter),Number(verseNumber));setVerse(v);if(v){const existing=await getManagedTranslation(v.id,language);setItem(existing);setText(existing?.text??"");setTranslator(existing?.translator??"");setSource(existing?.source??"");setLicense(existing?.license??"");setNotes(existing?.notes??"");}};useEffect(()=>{void load();},[chapter,verseNumber,language]);
const canPublish=useMemo(()=>item?.reviewStatus==="HUMAN_REVIEWED",[item]);
const save=async(status:ReviewStatus)=>{if(!verse)return;try{const next=await saveManagedTranslation({verseId:verse.id,language,text,translator:translator||null,source:source||null,license:license||null,notes:notes||null,publisher:null,sourceUrl:null,reviewStatus:status});setItem(next);Alert.alert("Saved",`Translation status: ${status}`);}catch(e){Alert.alert("Cannot save",e instanceof Error?e.message:"Please try again.")}};
const changeStatus=async(status:ReviewStatus)=>{if(status==="PUBLISHED"&&!canPublish){Alert.alert("Publishing blocked","A translation must be Human Reviewed before it can be Published.");return;}if(!verse)return;try{const next=await updateTranslationStatus(verse.id,language,status);setItem(next);Alert.alert("Status updated",status);}catch(e){Alert.alert("Status blocked",e instanceof Error?e.message:"Please review the translation first.")}};
return <Screen><Text style={styles.title}>Translation Workflow</Text><Text style={styles.muted}>Verified Sanskrit is read-only. Admins edit Kannada, Hindi and English translations with provenance and review metadata.</Text><View style={styles.row}><Field label="Chapter" value={chapter} setValue={setChapter}/><Field label="Verse" value={verseNumber} setValue={setVerseNumber}/></View><Text style={styles.label}>Language</Text><View style={styles.row}>{TRANSLATION_LANGUAGES.map(l=><Choice key={l} selected={language===l} label={LANGUAGE_LABELS[l]} onPress={()=>setLanguage(l)}/>)}</View>{verse?<View style={styles.card}><Text style={styles.label}>Original Sanskrit</Text><Text accessibilityRole="text" style={styles.sanskrit}>{verse.sanskrit}</Text></View>:<Text style={styles.muted}>Verse not found.</Text>}<Field label="Translation" value={text} setValue={setText} multiline/><Field label="Translator" value={translator} setValue={setTranslator}/><Field label="Source" value={source} setValue={setSource}/><Field label="License" value={license} setValue={setLicense}/><Field label="Notes" value={notes} setValue={setNotes} multiline/><Text style={styles.label}>Workflow</Text><View style={styles.row}>{statuses.map(s=><Choice key={s} selected={item?.reviewStatus===s} label={s.replace(/_/g," ")} onPress={()=>s==="DRAFT"||s==="REVIEW_REQUIRED"||s==="HUMAN_REVIEWED"?void save(s):void changeStatus(s)}/>)}</View><Text style={styles.warning}>{canPublish?"Human Reviewed: publishing is allowed after explicit admin action.":"Publishing locked: only Human Reviewed content can be published."}</Text><Pressable accessibilityRole="button" onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>Back to Admin</Text></Pressable></Screen>}
function Field({label,value,setValue,multiline=false}:{label:string;value:string;setValue:(v:string)=>void;multiline?:boolean}){return <View><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={setValue} multiline={multiline} textAlignVertical={multiline?"top":"center"} style={[styles.input,multiline&&styles.multiline]}/></View>};function Choice({selected,label,onPress}:{selected:boolean;label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.choice,selected&&styles.choiceSelected]}><Text style={[styles.choiceText,selected&&styles.choiceSelectedText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({title:{fontSize:30,fontWeight:"800",color:colors.ink},muted:{color:colors.muted,fontSize:14,lineHeight:22,marginTop:spacing.sm},row:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},card:{marginTop:spacing.lg,padding:spacing.lg,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.paper},label:{color:colors.ink,fontSize:13,fontWeight:"800",marginTop:spacing.md,marginBottom:spacing.xs},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,paddingHorizontal:spacing.md,backgroundColor:colors.paper,color:colors.ink},multiline:{minHeight:120,paddingTop:spacing.md},sanskrit:{fontFamily:"Noto Sans Devanagari",fontSize:24,lineHeight:44,color:colors.ink,textAlign:"center"},choice:{minHeight:42,paddingHorizontal:spacing.md,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.paper,justifyContent:"center"},choiceSelected:{backgroundColor:colors.navy,borderColor:colors.navy},choiceText:{color:colors.ink,fontWeight:"800",fontSize:12},choiceSelectedText:{color:colors.ivory},warning:{marginTop:spacing.lg,color:colors.saffron,fontWeight:"800",lineHeight:20},back:{marginTop:spacing.lg,minHeight:48,justifyContent:"center",alignItems:"center"},backText:{color:colors.purpleSoft,fontWeight:"800"}});
