ALTER TABLE "Audio" ADD COLUMN "provider" TEXT;
ALTER TABLE "Audio" ADD COLUMN "voice" TEXT;
ALTER TABLE "Audio" ADD COLUMN "speed" DOUBLE PRECISION;
ALTER TABLE "Audio" ADD COLUMN "approvedBy" TEXT;
